import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
const root=new URL("../",import.meta.url);
const read=p=>readFile(new URL(p,root),"utf8");
const runtime=await read("src/studio-widget-studio-v366.js");
const css=await read("src/studio-widget-studio-v366.css");
const studio=await read("src/ThemeStudio.jsx");
assert.match(runtime,/STUDIO_WIDGET_STUDIO_RELEASE_V366/);
assert.match(runtime,/getBoundingClientRect/);
assert.match(runtime,/sidebarRight/);
assert.match(runtime,/setInterval\(schedule,250\)/);
assert.match(runtime,/z-index/);
assert.match(css,/data-v366-widget="hard-sidebar-bound"/);
assert.match(css,/grid-template-columns:minmax\(0,1fr\) 44px/);
assert.match(css,/overflow-wrap:anywhere/);
assert.match(studio,/studio-widget-studio-v366\.js/);
