import fs from "node:fs";
import assert from "node:assert/strict";
const jsx=fs.readFileSync("src/ThemeStudio.jsx","utf8");
const js=fs.readFileSync("src/studio-theme-code-editor-v363.js","utf8");
const css=fs.readFileSync("src/studio-theme-code-editor-v363.css","utf8");
assert.match(jsx,/studio-theme-code-editor-v363\.js/);
assert.doesNotMatch(jsx,/studio-theme-code-editor-v361\.js|studio-theme-code-editor-v362\.js/);
assert.match(js,/Array\.from\(\{length:10000\}/);
assert.match(js,/data\.v363CodeEditor/);
assert.match(js,/getBoundingClientRect/);
assert.match(css,/data-v363-code-editor="ready"/);
assert.match(css,/grid-template-areas:"preview" "code"/);
assert.match(css,/grid-template-columns:minmax\(0,1fr\)/);
assert.match(css,/tn-code-gutter-v363/);
assert.match(css,/white-space:pre-wrap/);
assert.match(css,/overflow-wrap:anywhere/);
assert.match(css,/data-editor-split-v105="true"/);
assert.match(css,/data-editor-split-v106="true"/);
console.log("v363 stable vertical code editor checks passed");