export const DOMAIN_MANAGER_V80_CSS = String.raw`
:host{all:initial;display:block;position:relative;inset:auto;transform:none;width:100%;max-width:100%;min-width:0;height:auto;min-height:0;overflow:visible;contain:layout style;isolation:isolate;color:#17243d;font-family:"DM Sans",Arial,sans-serif;font-size:16px;line-height:1.5;-webkit-text-size-adjust:100%;text-size-adjust:100%}
*,*::before,*::after{box-sizing:border-box;min-width:0}
button,input{font:inherit}
button{cursor:pointer}
svg{width:20px;height:20px;fill:none;stroke:currentColor;stroke-width:1.8;stroke-linecap:round;stroke-linejoin:round}
.app{display:block;position:relative;inset:auto;transform:none;float:none;width:100%;max-width:1480px;min-height:0;height:auto;margin:0 auto;padding:30px clamp(16px,3.5vw,46px) 72px;overflow:visible;background:#f5f7fb;font-size:16px;line-height:1.5}
.app :where(header,section,article,aside,div,span,label,form,nav,footer,h1,h2,h3,h4,p,small,b,strong,em,i,input,button){transform:none;float:none}
.app :where(h1,h2,h3,h4,p,small,b,strong,em,i,span,label){max-width:100%;overflow-wrap:anywhere;word-break:normal}
.hero{position:relative;display:flex;align-items:flex-start;justify-content:space-between;gap:20px;height:auto;min-height:0;margin:0 0 22px}
.eyebrow{display:block;position:relative;margin:0;color:#2d6edf;font-size:10px;font-weight:900;line-height:1.35;letter-spacing:.18em;text-transform:uppercase}
h1,h2,h3,h4,p{position:relative;margin:0}
h1{margin:8px 0 10px;color:#14233c;font-family:"Playfair Display",Georgia,serif;font-size:clamp(38px,4.8vw,66px);font-weight:600;line-height:1.02;letter-spacing:-.035em;white-space:normal}
.hero p{max-width:880px;color:#6f7c90;font-size:13px;line-height:1.65;white-space:normal}
.btn,.link{position:relative;inset:auto;transform:none;min-height:42px;height:auto;display:inline-flex;align-items:center;justify-content:center;gap:8px;border:0;border-radius:11px;padding:10px 14px;text-decoration:none;font-size:12px;font-weight:850;line-height:1.25;white-space:normal}
.btn:disabled{opacity:.5;cursor:not-allowed}
.btn.primary{background:#2d6edf;color:#fff}
.btn.secondary,.link{background:#edf3ff;color:#2d6edf}
.btn.danger{background:#fff0f2;color:#a73544}
.card{position:relative;inset:auto;transform:none;height:auto;min-height:0;margin:0 0 16px;border:1px solid #dfe6ef;border-radius:20px;background:#fff;box-shadow:0 12px 32px rgba(25,49,91,.05);overflow:hidden}
.notice{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:16px 18px;border-color:#efcfd5;background:#fff2f4}
.notice b{display:block;color:#8f2e3a}.notice p{color:#8d5660;font-size:12px}
.workspace{position:relative;display:grid;grid-template-columns:minmax(0,1fr) minmax(290px,430px);gap:20px;align-items:center;height:auto;min-height:0;padding:20px 22px;background:linear-gradient(135deg,#fff,#f4f8ff)}
.workspace h2{margin:5px 0;color:#17243d;font-size:24px;line-height:1.2;white-space:normal}.workspace p{color:#6d7b91;font-size:12px;line-height:1.55;overflow-wrap:anywhere;white-space:normal}
.workspace aside{position:relative;height:auto;min-height:0;padding:14px 16px;border:1px solid #dbe4f0;border-radius:14px;background:#fff}.workspace aside b{font-size:12px}.workspace aside p{margin-top:4px;font-size:11px;line-height:1.55}
.metrics{position:relative;display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;height:auto;min-height:0;margin:0 0 16px}
.metric{position:relative;display:grid;grid-template-columns:34px minmax(0,1fr);gap:2px 10px;align-items:center;height:auto;min-height:0;padding:15px 16px;border:1px solid #dfe6ef;border-radius:15px;background:#fff}
.metric svg{grid-row:1/3;color:#2d6edf}.metric span{color:#718096;font-size:11px}.metric b{font-size:22px;line-height:1.2}
.free{position:relative;display:grid;grid-template-columns:58px minmax(0,1fr) auto;gap:18px;align-items:center;height:auto;min-height:0;padding:22px;background:linear-gradient(135deg,#fff,#f4f8ff)}
.iconbox{position:relative;width:58px;height:58px;display:grid;place-items:center;border-radius:18px;background:#e9f1ff;color:#2d6edf}.iconbox svg{width:28px;height:28px}
.free h2{margin:5px 0;color:#17243d;font-size:22px;line-height:1.2;white-space:normal;overflow-wrap:anywhere}.free p{color:#6f7c90;font-size:12px;line-height:1.55}.free aside{position:relative;display:flex;align-items:center;justify-content:flex-end;gap:8px;flex-wrap:wrap;height:auto;min-height:0}
.badge{position:relative;display:inline-flex;align-items:center;border-radius:999px;padding:7px 10px;background:#fff3d6;color:#8c6616;font-size:10px;line-height:1.2;font-style:normal;font-weight:850;white-space:normal}.badge.active{background:#e8f8ef;color:#17784f}.badge.danger{background:#fff0f2;color:#a73544}.badge.pending{background:#fff4da;color:#8b6518}
.section-head{position:relative;display:grid;grid-template-columns:46px minmax(0,1fr);gap:14px;align-items:start;height:auto;min-height:0;padding:22px;border-bottom:1px solid #e6ebf2}.section-head>div{position:relative;display:block;height:auto;min-height:0}.section-head .iconbox{width:46px;height:46px;border-radius:14px}.section-head h2{margin:5px 0 6px;font-size:23px;line-height:1.2;white-space:normal}.section-head p{max-width:850px;color:#6f7c90;font-size:12px;line-height:1.6;white-space:normal}
.register-form{position:relative;display:grid;grid-template-columns:minmax(0,1fr) auto;gap:14px;align-items:end;height:auto;min-height:0;padding:22px}
.field{position:relative;display:grid;grid-template-columns:minmax(0,1fr);align-content:start;gap:7px;width:100%;height:auto;min-height:0;margin:0}.field>span{position:relative;display:block;width:100%;height:auto;min-height:0;margin:0;font-size:12px;font-weight:850;line-height:1.45;white-space:normal}.field small{position:relative;display:block;width:100%;height:auto;min-height:0;margin:0;color:#7a8799;font-size:11px;line-height:1.45;white-space:normal}
.input{position:relative;inset:auto;display:block;width:100%;max-width:100%;min-width:0;height:50px;min-height:50px;margin:0;border:1px solid #cbd6e5;border-radius:12px;padding:0 14px;background:#fff;color:#17243d;font-size:16px;line-height:1.25;outline:none}.input:focus{border-color:#2d6edf;box-shadow:0 0 0 3px rgba(45,110,223,.1)}
.provider-note{position:relative;display:flex;align-items:center;gap:9px;height:auto;min-height:0;margin:0 22px 22px;padding:12px 14px;border-radius:12px;background:#edf9f3;color:#1d754f;font-size:12px;line-height:1.5;white-space:normal}
.domain-list-head,.audit-head{position:relative;display:flex;align-items:flex-start;justify-content:space-between;gap:16px;height:auto;min-height:0;padding:22px;border-bottom:1px solid #e6ebf2}.domain-list-head h2,.audit-head h2{margin:5px 0 6px;font-size:23px;line-height:1.2;white-space:normal}.domain-list-head p,.audit-head p{color:#6f7c90;font-size:12px;line-height:1.55;white-space:normal}
.empty{min-height:220px;display:grid;place-items:center;padding:30px;text-align:center;color:#7a8798}.empty svg{width:34px;height:34px;color:#2d6edf}.empty h3{margin:10px 0 4px;color:#17243d}
.domain{position:relative;height:auto;min-height:0;margin:18px;border:1px solid #dce4ef;border-radius:18px;background:#fbfcfe;overflow:hidden}
.domain>header{position:relative;display:flex;align-items:flex-start;justify-content:space-between;gap:14px;height:auto;min-height:0;padding:18px;background:#fff;border-bottom:1px solid #e5eaf1}.domain-name{display:grid;grid-template-columns:46px minmax(0,1fr);gap:13px;align-items:center}.domain-name .iconbox{width:46px;height:46px;border-radius:14px}.domain-name h3{margin:4px 0;font-size:20px;line-height:1.2;white-space:normal;overflow-wrap:anywhere}.domain-name p{color:#6f7c90;font-size:12px;line-height:1.55}.domain-badges{display:flex;gap:7px;flex-wrap:wrap}
.ns{position:relative;height:auto;min-height:0;margin:16px;border:1px solid #dce4ef;border-radius:14px;overflow:hidden;background:#fff}.ns>header{position:relative;display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px;align-items:center;height:auto;min-height:0;padding:13px 14px;background:#f6f8fc}.ns>header b{display:block}.ns-row{position:relative;display:grid;grid-template-columns:110px minmax(0,1fr) 40px;gap:10px;align-items:center;height:auto;min-height:0;padding:12px 14px;border-top:1px solid #e7ebf1}.ns-row code{font-size:12px;overflow-wrap:anywhere}.icon-btn{width:38px;height:38px;display:grid;place-items:center;border:0;border-radius:10px;background:#eef3fb;color:#2d6edf}
.domain-error{position:relative;height:auto;min-height:0;margin:16px;padding:12px 14px;border-radius:12px;background:#fff0f2;color:#a8323f;font-size:12px;line-height:1.5}
.actions{position:relative;display:flex;gap:9px;flex-wrap:wrap;height:auto;min-height:0;padding:0 18px 18px}
.routing{position:relative;height:auto;min-height:0;padding:18px;border-top:1px solid #e5eaf1;background:#fff}.routing h4{margin:4px 0;font-size:18px;line-height:1.2}.routing p{color:#6f7c90;font-size:12px;line-height:1.55}
.address{position:relative;display:grid;grid-template-columns:minmax(0,1fr) auto auto;gap:10px;align-items:center;height:auto;min-height:0;padding:12px 0;border-top:1px solid #e8edf3}.address b,.address small{display:block;overflow-wrap:anywhere}.address small{margin-top:3px;color:#758196;font-size:11px}
.switch{min-width:104px;min-height:40px;height:auto;display:inline-flex;align-items:center;justify-content:center;gap:7px;border:0;border-radius:11px;padding:8px 12px;background:#edf1f6;color:#617087;font-size:11px;font-weight:850}.switch span{width:18px;height:18px;border-radius:50%;background:#fff;box-shadow:0 1px 4px rgba(0,0,0,.18)}.switch.on{background:#e8f8ef;color:#17784f}
.locked{border-radius:999px;padding:7px 11px;background:#e8f8ef;color:#17784f;font-size:10px;font-style:normal;font-weight:850}
.address-form{position:relative;display:grid;grid-template-columns:minmax(0,1fr) auto;gap:12px;align-items:end;height:auto;min-height:0;margin-top:12px;padding-top:14px;border-top:1px solid #e8edf3}.compound{display:grid;grid-template-columns:minmax(0,1fr) auto;border:1px solid #cad5e4;border-radius:12px;overflow:hidden}.compound .input{border:0;border-radius:0;box-shadow:none}.compound strong{display:flex;align-items:center;max-width:320px;padding:0 12px;background:#eef3fa;color:#65738a;font-size:11px;overflow-wrap:anywhere}
.audit-results{position:relative;height:auto;min-height:0;padding:0 22px 18px}.audit-row{position:relative;display:grid;grid-template-columns:38px minmax(0,1fr) auto;gap:11px;align-items:center;height:auto;min-height:0;padding:12px 0;border-top:1px solid #e7ebf1}.audit-row>span{width:36px;height:36px;display:grid;place-items:center;border-radius:11px;background:#fff4da;color:#8b6518}.audit-row>span.ok{background:#e8f8ef;color:#17784f}.audit-row b,.audit-row small{display:block;overflow-wrap:anywhere}.audit-row small{color:#758196}.audit-row i{font-size:11px;font-style:normal;color:#617087}
.toast{position:fixed;right:18px;bottom:18px;z-index:2147483640;max-width:min(440px,calc(100vw - 36px));padding:13px 16px;border-radius:12px;background:#19345f;color:#fff;box-shadow:0 16px 36px rgba(9,28,59,.26);font-size:13px;line-height:1.5}.toast.danger{background:#a82f3d}
@media(max-width:1100px){.workspace{grid-template-columns:minmax(0,1fr)}.metrics{grid-template-columns:repeat(2,minmax(0,1fr))}.free{grid-template-columns:54px minmax(0,1fr)}.free aside{grid-column:1/-1;justify-content:flex-start}.register-form,.address-form{grid-template-columns:minmax(0,1fr);align-items:stretch}.register-form .btn,.address-form .btn{justify-self:start}}
@media(max-width:700px){:host{font-size:16px}.app{padding:18px 12px max(56px,env(safe-area-inset-bottom));font-size:16px;overflow-x:hidden}.hero{display:grid;grid-template-columns:minmax(0,1fr);gap:12px;margin-bottom:18px}.hero .btn{justify-self:start;margin:0}h1{font-size:clamp(34px,10vw,48px);line-height:1.04;margin:6px 0 9px}.hero p{font-size:13px;line-height:1.6}.workspace,.free,.section-head,.register-form{padding:16px}.workspace{display:grid;grid-template-columns:minmax(0,1fr);gap:14px}.workspace h2{font-size:21px;line-height:1.2}.workspace aside{width:100%}.metrics{grid-template-columns:repeat(2,minmax(0,1fr))}.free{display:grid;grid-template-columns:48px minmax(0,1fr);gap:12px;align-items:start}.free .iconbox{width:48px;height:48px;border-radius:14px}.free h2{font-size:19px;line-height:1.2}.free aside{grid-column:1/-1;justify-content:flex-start}.section-head{display:grid;grid-template-columns:40px minmax(0,1fr);gap:12px;padding:16px}.section-head .iconbox{width:40px;height:40px}.section-head h2{font-size:21px;line-height:1.2;margin:4px 0 6px}.section-head p{font-size:12px;line-height:1.55}.register-form{display:grid;grid-template-columns:minmax(0,1fr);gap:14px;align-items:stretch}.field{gap:8px}.input{height:50px;min-height:50px;font-size:16px}.register-form>.btn{justify-self:stretch;width:100%;min-height:48px}.provider-note{margin:0 16px 16px;padding:12px;font-size:12px}.domain-list-head,.audit-head{display:grid;grid-template-columns:minmax(0,1fr);gap:10px;padding:16px}.audit-head .btn{justify-self:start;margin:0}.domain{margin:12px}.domain>header{display:grid;grid-template-columns:minmax(0,1fr);gap:10px}.domain-badges{margin-top:0}.ns-row{grid-template-columns:minmax(0,1fr) 40px}.ns-row span{grid-column:1/-1}.address{grid-template-columns:minmax(0,1fr) auto}.address .icon-btn{grid-column:2}.compound{grid-template-columns:minmax(0,1fr)}.compound strong{max-width:none;min-height:38px}.audit-row{grid-template-columns:38px minmax(0,1fr)}.audit-row i{grid-column:2}}
@media(max-width:430px){.app{padding-left:10px;padding-right:10px}h1{font-size:clamp(31px,10.5vw,42px)}.metrics{grid-template-columns:minmax(0,1fr)}.free{grid-template-columns:42px minmax(0,1fr);padding:14px}.free .iconbox{width:42px;height:42px}.section-head{grid-template-columns:38px minmax(0,1fr);padding:14px}.section-head .iconbox{width:38px;height:38px}.register-form{padding:14px}.provider-note{margin:0 14px 14px}}
/* Marker: domain-manager-flow-integrity-v111 mobile-pwa-desktop-text-zoom-safe-v111 */
`;
