create extension if not exists pgcrypto;
create type public.member_role as enum ('owner','admin','editor','author','contributor','viewer');
create type public.content_status as enum ('draft','review','scheduled','published','archived');
create type public.content_kind as enum ('article','page');
create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, display_name text not null default '', avatar_url text, locale text not null default 'id-ID', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.sites (id uuid primary key default gen_random_uuid(), owner_id uuid not null references public.profiles(id) on delete cascade, name text not null check (char_length(name) between 2 and 100), slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'), description text not null default '', theme text not null default 'Editorial', settings jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.site_members (site_id uuid not null references public.sites(id) on delete cascade, user_id uuid not null references public.profiles(id) on delete cascade, role public.member_role not null default 'viewer', created_at timestamptz not null default now(), primary key (site_id, user_id));
create table public.contents (id uuid primary key default gen_random_uuid(), site_id uuid not null references public.sites(id) on delete cascade, author_id uuid not null references public.profiles(id), kind public.content_kind not null default 'article', title text not null default 'Tanpa judul', slug text not null, body_html text not null default '', excerpt text not null default '', status public.content_status not null default 'draft', seo jsonb not null default '{}'::jsonb, published_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(site_id, slug));
create table public.content_revisions (id bigint generated always as identity primary key, content_id uuid not null references public.contents(id) on delete cascade, editor_id uuid not null references public.profiles(id), snapshot jsonb not null, created_at timestamptz not null default now());
create index contents_site_status_idx on public.contents(site_id, status, updated_at desc);
create index revisions_content_idx on public.content_revisions(content_id, created_at desc);
create function public.is_site_member(target_site uuid) returns boolean language sql stable security definer set search_path = public as $$ select exists(select 1 from public.site_members where site_id = target_site and user_id = auth.uid()) $$;
create function public.can_edit_site(target_site uuid) returns boolean language sql stable security definer set search_path = public as $$ select exists(select 1 from public.site_members where site_id = target_site and user_id = auth.uid() and role in ('owner','admin','editor','author')) $$;
alter table public.profiles enable row level security; alter table public.sites enable row level security; alter table public.site_members enable row level security; alter table public.contents enable row level security; alter table public.content_revisions enable row level security;
create policy "profiles self read" on public.profiles for select using (id = auth.uid());
create policy "profiles self update" on public.profiles for update using (id = auth.uid()) with check (id = auth.uid());
create policy "members see sites" on public.sites for select using (public.is_site_member(id));
create policy "owners create sites" on public.sites for insert with check (owner_id = auth.uid());
create policy "admins update sites" on public.sites for update using (public.can_edit_site(id));
create policy "members see memberships" on public.site_members for select using (public.is_site_member(site_id));
create policy "members read content" on public.contents for select using (public.is_site_member(site_id) or status = 'published');
create policy "editors create content" on public.contents for insert with check (public.can_edit_site(site_id) and author_id = auth.uid());
create policy "editors update content" on public.contents for update using (public.can_edit_site(site_id));
create policy "editors remove content" on public.contents for delete using (public.can_edit_site(site_id));
create policy "editors read revisions" on public.content_revisions for select using (exists(select 1 from public.contents c where c.id = content_id and public.can_edit_site(c.site_id)));
create policy "editors create revisions" on public.content_revisions for insert with check (editor_id = auth.uid() and exists(select 1 from public.contents c where c.id = content_id and public.can_edit_site(c.site_id)));
create function public.handle_new_user() returns trigger language plpgsql security definer set search_path = public as $$ begin insert into public.profiles(id, display_name, avatar_url) values(new.id, coalesce(new.raw_user_meta_data->>'full_name', new.email, ''), new.raw_user_meta_data->>'avatar_url'); return new; end; $$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
create function public.add_owner_membership() returns trigger language plpgsql security definer set search_path = public as $$ begin insert into public.site_members(site_id, user_id, role) values(new.id, new.owner_id, 'owner'); return new; end; $$;
create trigger on_site_created after insert on public.sites for each row execute procedure public.add_owner_membership();
