alter table public.billing_orders add column if not exists site_id uuid references public.sites(id) on delete set null;
alter table public.billing_orders add column if not exists idempotency_key text;
alter table public.billing_orders add column if not exists invoice_number text;
alter table public.billing_orders add column if not exists payment_method text not null default 'paypal';
alter table public.billing_orders add column if not exists provider_capture_id text;
alter table public.billing_orders add column if not exists provider_event_id text;
alter table public.billing_orders add column if not exists failure_code text;
alter table public.billing_orders add column if not exists failure_message text;
alter table public.billing_orders add column if not exists paid_at timestamptz;
alter table public.billing_orders add column if not exists plan_expires_at timestamptz;
alter table public.billing_orders add column if not exists refunded_at timestamptz;
alter table public.billing_orders add column if not exists receipt_url text;
alter table public.billing_orders add column if not exists metadata jsonb not null default '{}'::jsonb;

create unique index if not exists billing_orders_idempotency_idx on public.billing_orders(idempotency_key) where idempotency_key is not null;
create unique index if not exists billing_orders_invoice_number_idx on public.billing_orders(invoice_number) where invoice_number is not null;
create index if not exists billing_orders_user_created_idx on public.billing_orders(user_id,created_at desc);
create index if not exists billing_orders_status_created_idx on public.billing_orders(status,created_at desc);
create index if not exists billing_orders_site_created_idx on public.billing_orders(site_id,created_at desc) where site_id is not null;

create table if not exists public.billing_webhook_events (
  id bigint generated by default as identity primary key,
  provider text not null,
  provider_event_id text not null,
  event_type text not null,
  status text not null default 'received' check (status in ('received','processed','ignored','failed')),
  provider_order_id text,
  provider_capture_id text,
  payload jsonb not null default '{}'::jsonb,
  error_message text,
  received_at timestamptz not null default now(),
  processed_at timestamptz,
  unique(provider,provider_event_id)
);
create index if not exists billing_webhook_order_idx on public.billing_webhook_events(provider,provider_order_id,received_at desc);
alter table public.billing_webhook_events enable row level security;
revoke all on public.billing_webhook_events from anon,authenticated;

create table if not exists public.site_backup_events (
  id bigint generated by default as identity primary key,
  site_id uuid not null references public.sites(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  action text not null check (action in ('export','restore')),
  document_count integer not null default 0 check (document_count >= 0),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists site_backup_events_user_created_idx on public.site_backup_events(user_id,created_at desc);
create index if not exists site_backup_events_site_created_idx on public.site_backup_events(site_id,created_at desc);
alter table public.site_backup_events enable row level security;
drop policy if exists "site_backup_events_own_select" on public.site_backup_events;
create policy "site_backup_events_own_select" on public.site_backup_events for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists "site_backup_events_own_insert" on public.site_backup_events;
create policy "site_backup_events_own_insert" on public.site_backup_events for insert to authenticated with check ((select auth.uid()) = user_id and private.is_site_member(site_id));
grant select,insert on public.site_backup_events to authenticated;
